#!/usr/bin/env node
/**
 * build-catalog.js — generate catalog.js from catalog.json + methods.json
 *
 * Usage:
 *   node build-catalog.js            rebuild catalog.js
 *   node build-catalog.js --check    exit 1 if catalog.js is stale (no write)
 *
 * WHY THIS EXISTS
 * ---------------
 * catalog.json and methods.json are the sources of truth — hand-edited,
 * git-diffable, queryable. But index.html has to run from file://, and a
 * browser will not fetch() a local .json file: it treats it as an opaque
 * origin and blocks the request. A <script src> tag is not subject to that.
 *
 * So catalog.js is a generated shim wrapping the same data in two globals.
 * Same reason graph-composer.html reads families.js and graph-sets.js
 * rather than .json.
 *
 * The hazard this script removes: before it existed, catalog.js was built
 * by an ad-hoc command that lived nowhere. Editing catalog.json changed
 * nothing on screen, silently, because the dashboard only ever reads the
 * generated file. Run --check from a hook or before publishing.
 */

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const DIR = __dirname;
const SOURCES = { catalog: 'catalog.json', methods: 'methods.json' };
const OUT = 'catalog.js';

function readSource(file) {
  const p = path.join(DIR, file);
  if (!fs.existsSync(p)) {
    console.error(`✗ missing source: ${file}`);
    process.exit(1);
  }
  const raw = fs.readFileSync(p, 'utf8');
  try {
    return { raw, data: JSON.parse(raw) };
  } catch (e) {
    console.error(`✗ ${file} is not valid JSON — ${e.message}`);
    process.exit(1);
  }
}

function build() {
  const cat = readSource(SOURCES.catalog);
  const met = readSource(SOURCES.methods);

  const stamp = {
    builtAt: new Date().toISOString().slice(0, 10),
    builtBy: 'build-catalog.js',
    sourceHashes: {
      'catalog.json': crypto.createHash('sha256').update(cat.raw).digest('hex').slice(0, 16),
      'methods.json': crypto.createHash('sha256').update(met.raw).digest('hex').slice(0, 16)
    }
  };

  const body =
    '/* GENERATED by build-catalog.js — do not edit.\n' +
    '   Edit catalog.json or methods.json, then run: node build-catalog.js */\n' +
    'window.RCN_BUILD = ' + JSON.stringify(stamp, null, 2) + ';\n' +
    'window.RCN_CATALOG = ' + JSON.stringify(cat.data, null, 2) + ';\n' +
    'window.RCN_METHODS = ' + JSON.stringify(met.data, null, 2) + ';\n';

  return { body, stamp, cat: cat.data, met: met.data };
}

function currentHashes() {
  const p = path.join(DIR, OUT);
  if (!fs.existsSync(p)) return null;
  const m = fs.readFileSync(p, 'utf8').match(/window\.RCN_BUILD = ([\s\S]*?);\nwindow\.RCN_CATALOG/);
  if (!m) return null;
  try { return JSON.parse(m[1]).sourceHashes; } catch (e) { return null; }
}

const built = build();
const check = process.argv.includes('--check');

if (check) {
  const have = currentHashes();
  const want = built.stamp.sourceHashes;
  const stale = !have || Object.keys(want).some(k => have[k] !== want[k]);
  if (stale) {
    console.error('✗ catalog.js is STALE — the dashboard is showing old data.');
    console.error('  Run: node tools/build-catalog.js');
    Object.keys(want).forEach(k => {
      if (!have || have[k] !== want[k]) console.error(`    changed: ${k}`);
    });
    process.exit(1);
  }
  console.log('✓ catalog.js is current');
  process.exit(0);
}

fs.writeFileSync(path.join(DIR, OUT), built.body);

const tools = built.cat.tools || [];
const methods = built.met.methods || [];
const live = tools.filter(t => t.status === 'live');
const noIntro = live.filter(t => !t.intro);
const byKind = methods.reduce((a, m) => (a[m.kind] = (a[m.kind] || 0) + 1, a), {});

console.log(`✓ wrote ${OUT}`);
console.log(`  ${tools.length} tools — ${live.length} live, ${noIntro.length} live with no intro`);
console.log(`  ${methods.length} methods — ` + Object.entries(byKind).map(([k, n]) => `${n} ${k}`).join(', '));
if (noIntro.length) console.log(`  needs an intro: ${noIntro.map(t => t.id).join(', ')}`);
