/* GENERATED by build-catalog.js — do not edit.
   Edit catalog.json or methods.json, then run: node build-catalog.js */
window.RCN_BUILD = {
  "builtAt": "2026-08-18",
  "builtBy": "build-catalog.js",
  "sourceHashes": {
    "catalog.json": "bfb1f10871350701",
    "methods.json": "b81662301e68fc51"
  }
};
window.RCN_CATALOG = {
  "_meta": {
    "version": "0.1",
    "generated": "2026-08-17",
    "authority": "Source of truth for the RCN Tools and Methods storefront and for how tools/ is organized. See docs/rcn-toolshelf-plan.html and docs/rcn-pathways.html.",
    "statusKey": {
      "live": "In use. Works, and someone other than the author could open it today.",
      "draft": "Exists and runs, but unfinished or undocumented. Not yet offered.",
      "dormant": "Not on the shelf. Reference, back office, superseded, or scratch."
    },
    "statusesAreProposals": "Every status below is Claude's reading of the repo on 2026-08-17 and awaits Marc's confirmation. Correct them here, not in the README.",
    "shelfKey": {
      "when-where": "Settings and context",
      "why": "Purposes, motives, beliefs",
      "who": "Roles and agency",
      "how-strategy": "Strategies and interventions",
      "how-mechanism": "Design and implementation",
      "what": "Outcomes and affordances",
      "workshop": "Kept, but not on the shelf"
    },
    "shelvesAre": "Marc's Six Nested Questions, from RCN Modeling Theory — not an invented list. A tool may sit on several shelves; shelf is a property here, never a folder on disk.",
    "governedBy": "Every use of every tool below is subject to the two governing models: the Social Action Tetrahedron (POIA) and Beauty/Good/Truth/Economy. 'All the models below these two must be informed by these or they will lead to no good.'",
    "familyKey": "Optional grouping for tools that ship as a product family, orthogonal to shelf.",
    "paths": "launch/intro/manual/example/deck are relative to tools/ unless they contain a slash.",
    "generator": "catalog.js is GENERATED from this file plus methods.json by build-catalog.js. Edit this file, then run: node tools/build-catalog.js. Nothing rebuilds it for you — index.html only ever reads the generated catalog.js, because a browser will not fetch() a local .json from file://. Run `node tools/build-catalog.js --check` to fail loudly if they have diverged."
  },
  "tools": [
    {
      "id": "rcn-map",
      "name": "RCN NDC Map",
      "what": "See where the neighborhood development cooperatives are, and what is happening in each place.",
      "shelf": [
        "when-where"
      ],
      "status": "live",
      "launch": "../maps/rcn_map.html",
      "intro": "../maps/rcn-map-intro.html",
      "manual": "../maps/rcn-map-manual.html",
      "example": null,
      "deck": "../maps/rcn-ndc-map.pptx",
      "note": "Live site is two files in one flat folder — rcn_map.html plus rcn_static_data.js loaded by flat name. The standalone build is a handout, explicitly not the live site."
    },
    {
      "id": "issue-polygon-map",
      "name": "Issue Polygon Map",
      "what": "Draw and name the parcels an issue actually covers, then share a link straight to one of them.",
      "shelf": [
        "when-where"
      ],
      "status": "live",
      "launch": "issue-polygon-map.html",
      "intro": "issue-polygon-map-intro.html",
      "manual": "issue-polygon-map-manual.html",
      "example": null,
      "deck": "rcn-issue-polygon-map-intro.pptx"
    },
    {
      "id": "rcn-timeline",
      "name": "RCN Timeline",
      "what": "Lay events out in time and test whether the order people remember actually holds.",
      "shelf": [
        "when-where"
      ],
      "status": "live",
      "launch": "rcn-timeline.html",
      "intro": "rcn-timeline-intro.html",
      "manual": "rcn-timeline-manual.html",
      "example": "t1-trace-timeline-demo.json",
      "deck": "rcn-timeline-intro.pptx",
      "usedIn": [
        "trace-then-timeline"
      ]
    },
    {
      "id": "graph-tool",
      "name": "RCN Graph Tool",
      "what": "Draw a system as nodes and edges, then argue about it together.",
      "shelf": [
        "why",
        "how-strategy",
        "how-mechanism"
      ],
      "status": "live",
      "launch": "graph-tool-v22.html",
      "intro": "graph-tool-intro.html",
      "manual": "graph-tool-manual.html",
      "example": "whatcom-homelessness-cld.json",
      "deck": "rcn-graph-tool-intro.pptx",
      "family": "graph",
      "note": "Filename stem disagrees with its intro and manual (graph-tool-v22 vs graph-tool-*). Rename opportunistically, not in a sweep. Modes answer different questions: CLD is Why, EIP is How-strategy, OPM and SFD are How-mechanism.",
      "usedIn": [
        "systemic-problem-solving",
        "trace-then-timeline",
        "shared-understanding-to-experiment"
      ]
    },
    {
      "id": "vester",
      "name": "Vester Influence Analysis",
      "what": "Find which variables actually drive a system, given its feedback structure — without needing numbers.",
      "shelf": [
        "why",
        "how-strategy"
      ],
      "status": "live",
      "launch": "../vester/",
      "intro": null,
      "manual": "../docs/vester-manual.html",
      "example": null,
      "deck": null,
      "note": "The only tool with a build step (Vite/React). Steps 0-5 built, through Partial Scenario simulation.",
      "usedIn": [
        "shared-understanding-to-experiment"
      ]
    },
    {
      "id": "schema-sunburst",
      "name": "RCN Schema Sunburst",
      "what": "See a whole schema at once, and find where a concept sits inside it.",
      "shelf": [
        "why"
      ],
      "status": "live",
      "launch": "schema-sunburst.html",
      "intro": "schema-sunburst-intro.html",
      "manual": "schema-sunburst-manual.html",
      "example": "eip-schema-cld.json",
      "deck": "rcn-schema-sunburst-intro.pptx",
      "family": "graph"
    },
    {
      "id": "sodoto-issuer",
      "name": "SODOTO Issuer",
      "what": "Vouch for someone who has learned a skill, and sign the credential yourself.",
      "shelf": [
        "who"
      ],
      "status": "live",
      "launch": "sodoto-issuer.html",
      "intro": "../docs/sodoto-intro.html",
      "manual": "sodoto-issuer-guide.html",
      "example": null,
      "deck": null,
      "family": "sodoto",
      "note": "Live on Wiki Café. Keys never on the server — each issuer enters their seed in their own browser."
    },
    {
      "id": "sodoto-onboard",
      "name": "Your SODOTO Identity",
      "what": "Mint your own identity on your own device. Nobody else holds it.",
      "shelf": [
        "who"
      ],
      "status": "live",
      "launch": "sodoto-onboard.html",
      "intro": "../docs/sodoto-intro.html",
      "manual": "../docs/sodoto-manual.html",
      "example": null,
      "deck": null,
      "family": "sodoto"
    },
    {
      "id": "sodoto-sign",
      "name": "Sign Your Gate",
      "what": "Sign off a learning gate — see one, do one, teach one.",
      "shelf": [
        "who"
      ],
      "status": "live",
      "launch": "sodoto-sign.html",
      "intro": null,
      "manual": null,
      "example": null,
      "deck": null,
      "family": "sodoto"
    },
    {
      "id": "cfa-dsc-creator",
      "name": "CfA-dSC Contract Creator",
      "what": "Write a two-party commitment that both sides can hold each other to.",
      "shelf": [
        "who"
      ],
      "status": "draft",
      "launch": "cfa-dsc-creator.html",
      "intro": null,
      "manual": "../cfa-dsc-handoff.md",
      "example": null,
      "deck": null
    },
    {
      "id": "my-support-network",
      "name": "My Support Network",
      "what": "Name the people who actually help, and see the gaps.",
      "shelf": [
        "who"
      ],
      "status": "draft",
      "launch": "my-support-network.html",
      "intro": null,
      "manual": null,
      "example": null,
      "deck": null,
      "family": "my-phs"
    },
    {
      "id": "graph-composer",
      "name": "RCN Graph Composer",
      "what": "Assemble a graph from families and schemas instead of drawing it from scratch.",
      "shelf": [
        "how-strategy"
      ],
      "status": "live",
      "launch": "graph-composer.html",
      "intro": "graph-composer-intro.html",
      "manual": "graph-composer-manual.html",
      "example": null,
      "deck": "rcn-graph-composer-intro.pptx",
      "family": "graph",
      "note": "Reads families.js and graph-sets.js as flat siblings — .js not .json, so it works from file://. Do not move those."
    },
    {
      "id": "eip-integration-explorer",
      "name": "EIP Integration Explorer",
      "what": "Walk the twelve EIP artifacts and see how they connect.",
      "shelf": [
        "how-strategy"
      ],
      "status": "draft",
      "launch": "eip_integration_explorer.html",
      "intro": null,
      "manual": null,
      "example": null,
      "deck": null,
      "note": "Underscored filename. Rename to hyphens when next touched."
    },
    {
      "id": "wardley-map-generator",
      "name": "Wardley Map Generator",
      "what": "Place what you depend on by how evolved it is, and see what to build versus buy.",
      "shelf": [
        "how-strategy"
      ],
      "status": "draft",
      "launch": "wardley-map-generator.html",
      "intro": null,
      "manual": "wardley-chat-card.md",
      "example": "wardley-bicycle-production.rcn.json",
      "deck": null
    },
    {
      "id": "my-health-choices",
      "name": "My Health Choices",
      "what": "See treatment options as a thousand dots, so the odds are something you can look at.",
      "shelf": [
        "how-strategy"
      ],
      "status": "live",
      "launch": "my-health-choices.html",
      "intro": null,
      "manual": "../scp-optionbox/authoring-guide.html",
      "example": null,
      "deck": null,
      "family": "my-phs"
    },
    {
      "id": "nrm-tripod-beta",
      "name": "NRM — Neighborhood Risk Management",
      "what": "Trace how a harm actually happened, back through the barriers that failed.",
      "shelf": [
        "how-mechanism"
      ],
      "status": "draft",
      "launch": "nrm-tripod-beta.html",
      "intro": null,
      "manual": "../docs/nrm-tripod-beta.md",
      "example": null,
      "deck": null,
      "note": "Also exists as a mode inside the Graph Tool."
    },
    {
      "id": "sfd-stella-approach",
      "name": "Stock & Flow — Stella Approach",
      "what": "See what accumulates and what drains it, once you have earned the right to numbers.",
      "shelf": [
        "how-mechanism"
      ],
      "status": "draft",
      "launch": "sfd-stella-approach.html",
      "intro": null,
      "manual": null,
      "example": null,
      "deck": null,
      "family": "graph"
    },
    {
      "id": "a3",
      "name": "A3 Problem Solving",
      "what": "Get a whole problem, its analysis and its countermeasure onto one sheet.",
      "shelf": [
        "how-mechanism"
      ],
      "status": "draft",
      "launch": "a3.html",
      "intro": null,
      "manual": null,
      "example": null,
      "deck": null,
      "embodies": "a3-problem-solving",
      "note": "A method wearing a tool's clothes — registry skill #15. It has ordered steps and gates, so it also wants a method page, and the two should point at each other. New, from a parallel session."
    },
    {
      "id": "graphjson-to-vensim",
      "name": "Graph JSON to Vensim CLD",
      "what": "Take a drawing out of the Graph Tool and into Vensim.",
      "shelf": [
        "how-mechanism"
      ],
      "status": "draft",
      "launch": "graphjson_to_vensim_cld.html",
      "intro": null,
      "manual": null,
      "example": null,
      "deck": null,
      "family": "graph"
    },
    {
      "id": "eip-local-finance",
      "name": "EIP Local Finance Analysis",
      "what": "See where a local economy's money comes from and where it leaves.",
      "shelf": [
        "how-mechanism"
      ],
      "status": "draft",
      "launch": "eip_local_finance_diagram.html",
      "intro": null,
      "manual": null,
      "example": null,
      "deck": null
    },
    {
      "id": "rcn-spc",
      "name": "RCN Process Behavior Charts",
      "what": "Tell a real change from noise, so a group stops arguing about both.",
      "shelf": [
        "what"
      ],
      "status": "live",
      "launch": "rcn-spc.html",
      "intro": "rcn-spc-intro.html",
      "manual": "rcn-spc-manual.html",
      "example": "spc-charts/p-laney.svg",
      "deck": "rcn-spc-intro.pptx",
      "usedIn": [
        "shared-understanding-to-experiment"
      ],
      "note": "Arrived fully documented, with its own schema at schemas/rcn-spc.md. The pattern every tool should follow."
    },
    {
      "id": "conversation-navigator",
      "name": "Conversation Navigator",
      "what": "Check whether a conversation is fooling itself, before acting on it.",
      "shelf": [
        "what"
      ],
      "status": "live",
      "launch": "bias-checker.html",
      "intro": "bias-checker-intro.html",
      "manual": "bias-checker-manual.html",
      "example": null,
      "deck": "rcn-bias-checker-intro.pptx",
      "note": "NAMING DRIFT: every page is titled Conversation Navigator; every filename says bias-checker. The tool was renamed and the files were not. Hosted at Wiki Café, not Firebase."
    },
    {
      "id": "positive-affect-score",
      "name": "Positive Affect Score",
      "what": "Measure whether people are actually doing better, not just whether the program ran.",
      "shelf": [
        "what"
      ],
      "status": "live",
      "launch": "positive-affect-score.html",
      "intro": "positive-affect-score-intro.html",
      "manual": "positive-affect-score-manual.html",
      "example": null,
      "deck": null
    },
    {
      "id": "evsm",
      "name": "eVSM Survey Cycle",
      "what": "Ask a whole organization where the value stalls, then read the answers together.",
      "shelf": [
        "what"
      ],
      "status": "draft",
      "launch": "evsm-svg-v3.html",
      "intro": null,
      "manual": null,
      "example": null,
      "deck": null,
      "family": "evsm",
      "embodies": "value-stream-mapping",
      "stages": [
        {
          "name": "Survey",
          "launch": "evsm-svg-v3.html"
        },
        {
          "name": "Aggregator",
          "launch": "evsm-aggregator.html"
        },
        {
          "name": "Respondent Report",
          "launch": "evsm-report.html"
        },
        {
          "name": "Excel Import / Export",
          "launch": "evsm_excel_tool.html"
        }
      ],
      "note": "ONE entry, not four. These are stages of a single method — registry skill #14. Needs one intro for the whole cycle, not four."
    },
    {
      "id": "my-health-picture",
      "name": "My Health Picture",
      "what": "See your own health as one picture you can hand to anyone caring for you.",
      "shelf": [
        "when-where",
        "what"
      ],
      "status": "live",
      "launch": "my-health-picture.html",
      "intro": null,
      "manual": null,
      "example": null,
      "deck": null,
      "family": "my-phs",
      "note": "Runs behind coupler-proxy.py on port 8766, with per-patient wiki routing."
    },
    {
      "id": "scp-chat",
      "name": "Prepare for Your Appointment",
      "what": "Work out what you actually want to ask, before you are in the room.",
      "shelf": [
        "what"
      ],
      "status": "draft",
      "launch": "scp-chat.html",
      "intro": null,
      "manual": null,
      "example": null,
      "deck": null,
      "family": "my-phs"
    },
    {
      "id": "more-outliner",
      "name": "MORE Outliner",
      "what": "Think in an outline that saves straight back into the wiki.",
      "shelf": [
        "how-strategy"
      ],
      "status": "live",
      "launch": "more-outliner.html",
      "intro": null,
      "manual": "more-outliner-manual.html",
      "example": null,
      "deck": null,
      "note": "Manual but no intro — the largest documentation gap on a live tool."
    },
    {
      "id": "groove",
      "name": "Groove Workspace",
      "what": "Work together in one place, and keep the trail of what was decided.",
      "shelf": [
        "who",
        "how-strategy"
      ],
      "status": "live",
      "launch": "../groove-workspace/",
      "intro": "groove-intro.html",
      "manual": "groove-manual.html",
      "example": "groove-workflow.json",
      "deck": null,
      "note": "Runs on port 3001."
    },
    {
      "id": "fedwiki-lineup",
      "name": "FedWiki Lineup & Print",
      "what": "Capture a row of wiki pages as one thing you can send or print.",
      "shelf": [
        "what"
      ],
      "status": "draft",
      "launch": "fedwiki-lineup-bookmarklet.html",
      "intro": null,
      "manual": null,
      "example": null,
      "deck": null
    },
    {
      "id": "rcn-icon-sheet",
      "name": "RCN House Icon Library",
      "what": "The house icons, on one sheet, for choosing from.",
      "shelf": [
        "workshop"
      ],
      "status": "dormant",
      "launch": "rcn-icon-sheet.html",
      "intro": null,
      "manual": null,
      "example": null,
      "deck": null,
      "note": "Reference, not a tool."
    },
    {
      "id": "patient-admin",
      "name": "Patient Provisioning",
      "what": "Set up a new person's wiki and seed their templates.",
      "shelf": [
        "workshop"
      ],
      "status": "dormant",
      "launch": "patient-admin.html",
      "intro": null,
      "manual": null,
      "example": null,
      "deck": null,
      "family": "my-phs",
      "note": "Back office. Not offered on the shelf."
    },
    {
      "id": "ibis-map-rcn",
      "name": "IBIS Map — Health Conversation",
      "what": "An argument mapped as issues, positions and arguments.",
      "shelf": [
        "workshop"
      ],
      "status": "dormant",
      "launch": "ibis-map-rcn.html",
      "intro": null,
      "manual": null,
      "example": null,
      "deck": null,
      "note": "An example, not a general tool."
    },
    {
      "id": "conversation-index",
      "name": "LLM Session Index",
      "what": "Marc's own index of past sessions.",
      "shelf": [
        "workshop"
      ],
      "status": "dormant",
      "launch": "conversation_index.html",
      "intro": null,
      "manual": null,
      "example": null,
      "deck": null,
      "note": "Personal. `conversation_index (old).html` is a download-mangled duplicate — delete it."
    },
    {
      "id": "session-builder",
      "name": "Session Instruction Builder",
      "what": "Build the instruction block for a working session.",
      "shelf": [
        "workshop"
      ],
      "status": "dormant",
      "launch": "session-builder (1).html",
      "intro": null,
      "manual": null,
      "example": null,
      "deck": null,
      "note": "Download-mangled filename. Rename to session-builder.html."
    },
    {
      "id": "contract-creator",
      "name": "Contract Creator",
      "what": "An earlier contract tool.",
      "shelf": [
        "workshop"
      ],
      "status": "dormant",
      "launch": "contract-creator.html",
      "intro": null,
      "manual": null,
      "example": null,
      "deck": null,
      "note": "Probably superseded by cfa-dsc-creator. Confirm, then archive."
    }
  ],
  "notOnTheShelf": {
    "comment": "Files in tools/ that are not tools. Listed so the alive-or-dead call is recorded rather than re-litigated.",
    "delete": [
      "checklist-test.html",
      "conversation_index (old).html"
    ],
    "moveToTests": [
      "sodoto-crypto-test.html"
    ],
    "areDocs": [
      "conversation-navigator-flow.html",
      "groove-presentation.html"
    ],
    "areScripts": [
      "create-rcn-graph-tool-page.html",
      "unwrap-md.js",
      "validate-rcn-graph.js",
      "brain-to-graph.py",
      "split-wa-health-aspects.py",
      "svg-to-graph-wa-health.py",
      "build-spc-fedwiki.js",
      "wardley-chat-to-rcn.js",
      "patch-wiki-pagejson.js",
      "test-timeline-solver.js",
      "build-lineup-bookmarklet.js"
    ],
    "areFlatSiblingsDoNotMove": [
      "families.js",
      "graph-sets.js",
      "edge-families.js",
      "rcn-icons.js",
      "stamp-legend-style.js",
      "fedwiki-lineup.js",
      "fedwiki-print.js",
      "sodoto-crypto.js",
      "bgte-12-triples.json"
    ],
    "areModelsNotTools": [
      "whatcom-homelessness-cld.json",
      "education-human-becoming-cld.json",
      "rba-hospital-pricing.rcn.json",
      "wardley-bicycle-production.rcn.json",
      "opm-relationships.rcn.json",
      "wa-health-as-network.json",
      "lop-whatcom-coop.rcn.json",
      "premium-position.rcn.json",
      "money-and-performance.rcn.json",
      "federation.rcn.json",
      "coop-fork.rcn.json",
      "four-adapters.rcn.json",
      "experiment-ramp.rcn.json",
      "rth-overview-cave-drawing.rcn.json",
      "sdoh-sorting-frame.rcn.json",
      "eip-schema-cld.json",
      "t1-trace-timeline-demo.json",
      "pomr-conversational-flow.json",
      "pomr-emc-value-flow.json",
      "pomr-physician-bandwidth.json",
      "pomr-physician-review-loop.json",
      "pomr-prior-diagnosis-audit.json",
      "pomr-problem-diagnosis.json",
      "neighborhood-cave-drawing.json",
      "southern-louisiana-actor-map-v22.json",
      "rcn-architecture-crown.rcn.json",
      "rcn-four-sequences.rcn.json",
      "rcn-three-files.rcn.json",
      "rcn-who-ostrom.rcn.json"
    ],
    "modelsNote": "These are PARTICULARS, in Marc's sense: 'the approach to modeling in RCN is to reveal rich perspectives in particular systems — NOT to create generalized models. Our generalizations will be published as Patterns.' They belong in models/ or tools/examples/, each linked to the pattern it was abstracted into. Only bgte-12-triples.json is loaded by path from a tool (the Graph Tool); the rest are only mentioned in manuals, so moving them costs four link fixes."
  }
};
window.RCN_METHODS = {
  "_meta": {
    "version": "0.1",
    "generated": "2026-08-18",
    "authority": "Pathways — ordered uses of tools. Sits beside catalog.json (tools) and the SODOTO Skills Registry (skills). One relation each: a method REQUIRES_SKILL, USES a tool, and a tool may EMBODY a method.",
    "sequenceLivesHere": "Never on the tool. A hammer is used in many processes and does a different job in each, so a tool cannot carry order. A tool's 'used in' list is derived by scanning this file, never typed.",
    "kinds": {
      "ontological": "What is true of ethical collective action. Not performed — checked against.",
      "diagnostic": "What to do when stuck. Returns a type, a scale, and a choice of production sequence.",
      "production": "Getting a thing built, delivered and taught.",
      "curricular": "The order in which a person learns the skills. What SODOTO certifies."
    },
    "confidence": "DERIVED from SODOTO attestations, never typed. A Do One earns one star; a Teach One whose learner then runs it earns the second. null means not yet computed. Zero stars is a normal, publishable state.",
    "transmissibility": "From the SODOTO Skills Registry — Active, Ready or Candidate. Orthogonal to confidence: a method can be proven and untransmissible, or teachable and untested.",
    "fallback": "Where to go when lost. Not a gate — a recovery available from any depth. Marc's rule: drop back to a causal loop diagram and diagram your sentences.",
    "governedBy": [
      "social-action-tetrahedron",
      "beauty-good-truth-economy"
    ],
    "stepFields": "question (what you are now ready to ask), tool (the instrument), does (its job IN THIS METHOD), produces, handoff (what you carry on, and in what shape), gate (what must be true first).",
    "statusNote": "Pathway pages are drafted in docs/rcn-pathways.html but not yet built as their own pages. Confidence and transmissibility marks are proposals awaiting Marc's confirmation."
  },
  "methods": [
    {
      "id": "systemic-problem-solving",
      "name": "Systemic Problem Solving",
      "kind": "diagnostic",
      "isRouter": true,
      "problem": "A neighbourhood problem keeps resisting the obvious fixes, and nobody agrees on what kind of problem it even is.",
      "context": "The front door. Entered when handy heuristics have failed and before any production pathway is chosen.",
      "confidence": 1,
      "transmissibility": "Candidate",
      "fallback": "graph-tool",
      "source": "Systemic Problem Solving (marc.relocalizecreativity.net)",
      "routesTo": [
        "shared-understanding-to-experiment",
        "inspiration-to-implementation",
        "collective-action-assessment"
      ],
      "steps": [
        {
          "question": "Will a rule of thumb do?",
          "tool": null,
          "does": "Try the handy heuristics first. Most things are not systems problems.",
          "gate": "Proceed only when the simple heuristics have actually failed. Entering the full pathway on a problem that did not need it is how these methods get a reputation for ceremony.",
          "produces": "A decision to continue or stop",
          "handoff": null
        },
        {
          "question": "What is connected to what?",
          "tool": "graph-tool",
          "does": "Draw the problem situation, naming the nodes AND the connections. Pen and paper first; move to the tool only once something interesting shows up.",
          "gate": null,
          "produces": "Graph JSON with named nodes and named edges",
          "handoff": "Everything downstream reads this graph. It is also the rung you return to from anywhere."
        },
        {
          "question": "What kind of problem is each part of this?",
          "tool": null,
          "does": "Type each subgraph separately with Cynefin — simple, complicated, complex, chaotic, disordered. A neighbourhood problem is almost never one type throughout.",
          "gate": null,
          "produces": "A typed set of subgraphs",
          "handoff": "The type selects the next pathway: complicated to design and engineering, complex to leverage and safe-to-fail experiments, chaotic to act-then-retype."
        },
        {
          "question": "When, where, why, who, how, and only then what?",
          "tool": null,
          "does": "Work the Six Nested Questions in order with the people who hold the situation. Two to four hours.",
          "gate": "The stakeholders must be in the room. Run alone this produces a document rather than a shared understanding, and the pathway depends on the second thing.",
          "produces": "A shared, ordered account of the situation",
          "handoff": "Answering What first is the standard failure — it produces solutions nobody will carry."
        },
        {
          "question": "Where is our power, and are we using all three kinds?",
          "tool": null,
          "does": "AIC — equal time appreciating the whole, weighing stakeholders' differing valuations, and designing production and control.",
          "gate": null,
          "produces": "A read on which of the three powers is available",
          "handoff": "Appreciate maps to Ideals, Influence to Persons, Control to Org and Action — the governing tetrahedron's vertices."
        },
        {
          "question": "Would running this be beautiful, good, true and economical?",
          "tool": null,
          "does": "The crown check, before committing.",
          "gate": "A plan that is efficient and ugly, or effective and untrue to its ecology, fails here and does not proceed on the strength of having passed everything else.",
          "produces": "Go or no-go",
          "handoff": null
        },
        {
          "question": "Which pathway now, and who has the standing to run it?",
          "tool": null,
          "does": "Choose the production pathway and check the registry for whether anyone present is certified in the skills it needs.",
          "gate": null,
          "produces": "A routed decision",
          "handoff": "Into one of the pathways in routesTo."
        }
      ]
    },
    {
      "id": "walking-the-tetrahedron",
      "name": "Walking the Tetrahedron",
      "kind": "ontological",
      "problem": "Everyone is working hard and nothing is coming of it. Something in the loop between people, ideals, organization and action is broken, and nobody can name which.",
      "context": "The governing model used as a check. Under an hour, no facilitator required.",
      "confidence": 0,
      "transmissibility": "Candidate",
      "requiresSkill": [
        "social-action-tetrahedron"
      ],
      "fallback": "graph-tool",
      "source": "Optimum Sequence Tetrahedron (marc.relocalizecreativity.net)",
      "steps": [
        {
          "question": "Do the persons here actually aspire to the ideal?",
          "tool": null,
          "does": "Test the Person to Ideal relation — Aspires to.",
          "produces": "A reading on Aspiration of Persons",
          "handoff": "If no, nothing downstream can be fixed by better organizing. Check whether the ideal was ever theirs or was handed to them.",
          "gate": null
        },
        {
          "question": "Does that ideal inspire an organization into being?",
          "tool": null,
          "does": "Test Ideal to Org — Inspires.",
          "produces": "A reading on Power of Inspiration of Org",
          "handoff": "If no, an ideal is held privately with no standing arrangement to pursue it.",
          "gate": null
        },
        {
          "question": "Does the organization facilitate action?",
          "tool": null,
          "does": "Test Org to Action — Facilitates.",
          "produces": "A reading on Quality of Facilitation",
          "handoff": "The commonest failure in practice: an organization exists, meets, and produces no action it has made easier.",
          "gate": null
        },
        {
          "question": "Does the action realize the originating ideal?",
          "tool": null,
          "does": "Test Action to Ideal — Realizes. These four are the thick arrows: the optimum sequence is the heavy path.",
          "produces": "A reading on Ideals Realized",
          "handoff": "If no, work is happening but has drifted from what it was for. The loop never closes and people burn out without knowing why.",
          "gate": null
        },
        {
          "question": "Is the action teaching the organization anything?",
          "tool": null,
          "does": "Test Action to Org — Teaches. Outside the optimum loop, checked last.",
          "produces": "A reading on Organizational Learning",
          "handoff": "This decides whether any of it compounds. It is SODOTO's Teach One at the scale of an institution.",
          "gate": null
        },
        {
          "question": "And does the whole of it come to good?",
          "tool": null,
          "does": "BGTE — the second half of the crown.",
          "produces": "A judgement on the whole",
          "handoff": "A tetrahedron whose four arrows all work, in service of something ugly, false or extractive, is a well-functioning machine pointed the wrong way.",
          "gate": null
        }
      ]
    },
    {
      "id": "collective-action-assessment",
      "name": "Collective Action Assessment",
      "kind": "diagnostic",
      "problem": "A neighbourhood holds something in common — water, road maintenance, a building, a fund — and nobody knows which parts of managing it are actually at risk.",
      "context": "The WHO shelf applied to a real commons. Ostrom's model, filled in for this place.",
      "confidence": 0,
      "transmissibility": "not in the registry",
      "fallback": "graph-tool",
      "source": "Collective Action Assessment (marc.relocalizecreativity.net)",
      "note": "The only method in the set whose output is a disagreement.",
      "steps": [
        {
          "question": "What do we actually hold in common?",
          "tool": null,
          "does": "Fill the template's blank nodes with this neighbourhood's real common-pool resources.",
          "gate": "The resource must be genuinely depletable AND open to access. If it is neither, this is the wrong model.",
          "produces": "A named list of local CPRs",
          "handoff": null
        },
        {
          "question": "Where is the risk, node by node?",
          "tool": null,
          "does": "Colour every node — red high risk, yellow low risk, green little or none now, blue undecidable now.",
          "gate": null,
          "produces": "One coloured assessment",
          "handoff": "Blue is a legitimate answer, not a failure to answer. A model with honest blue on it beats one coloured through."
        },
        {
          "question": "Do our associates see the same risks?",
          "tool": null,
          "does": "Have others do the exercise separately, before comparing.",
          "gate": "Assessments must be made independently. This is the entire point of the method and shortcutting it removes the finding.",
          "produces": "Several independent assessments",
          "handoff": null
        },
        {
          "question": "Where do we disagree — especially green versus red on the same node?",
          "tool": null,
          "does": "Discuss the differences over printed copies on a surface.",
          "gate": null,
          "produces": "The finding",
          "handoff": "A green-red split on one variable means two people are living in different systems. No single assessment could produce this."
        },
        {
          "question": "Which stage are we failing?",
          "tool": null,
          "does": "Read the reds by Ostrom stage — Origin (forming), Performance (managing), Survival (surviving).",
          "gate": null,
          "produces": "A staged diagnosis",
          "handoff": "Origin failures route to Systemic Problem Solving. Performance failures to Sofi-VSM. Survival failures mean conflict work first and everything else second."
        }
      ]
    },
    {
      "id": "shared-understanding-to-experiment",
      "name": "Shared Understanding to Experiment",
      "kind": "production",
      "problem": "The situation is genuinely complex — cause and effect are visible only in hindsight — and the group needs to intervene without pretending to predict.",
      "context": "Entered from Systemic Problem Solving when Cynefin says complex.",
      "confidence": 1,
      "transmissibility": "Active via causal-loop-diagramming",
      "requiresSkill": [
        "causal-loop-diagramming",
        "vesters-sensitivity-modeling"
      ],
      "fallback": "graph-tool",
      "source": "Leverage Points · Exploring Meadows & Ostrom",
      "steps": [
        {
          "question": "Do we see the same system?",
          "tool": "graph-tool",
          "does": "Climb the causal ladder in order: campfire conversation, cave drawing, then CLD.",
          "gate": null,
          "produces": "A shared causal picture",
          "handoff": "Shared only when people who disagree can point at the same picture and say where they disagree. The criterion for a cave drawing is that it is fit for finger pointing, not that it is right."
        },
        {
          "question": "Where would a small push do the most?",
          "tool": null,
          "does": "Work the 14 leverage points — Meadows' twelve plus Time Horizon and Awareness of Place — from the top down, not the bottom up.",
          "gate": null,
          "produces": "A ranked set of intervention points",
          "handoff": "Parameters and numbers are the weakest places to intervene; paradigm, goals and the power to self-organize are the strongest."
        },
        {
          "question": "What do we think will happen?",
          "tool": "vester",
          "does": "Find which variables are most influential given this feedback structure — not what the numbers will be.",
          "gate": "The numbers question. Do not move to simulation until you have earned it. CLDs have no numbers, and a simulation built before the feedback structure is understood is garbage dressed in numbers.",
          "produces": "Systemic roles — active, reactive, critical, buffering",
          "handoff": "Into a designed experiment, not a prediction."
        },
        {
          "question": "What actually changed?",
          "tool": "rcn-spc",
          "does": "Run the experiment, then read the result honestly.",
          "gate": null,
          "produces": "A process behaviour chart",
          "handoff": "Back into step 1 with a revised picture. A designed experiment is a way for humans to listen to systems as they communicate back to us. Without SPC a group will claim both success and failure from the same data."
        }
      ]
    },
    {
      "id": "inspiration-to-implementation",
      "name": "Inspiration to Implementation",
      "kind": "production",
      "problem": "Something needs to exist that does not, and the group is larger than a few friends — so the fifteen things a small group does intuitively must now be done on purpose.",
      "context": "The long arc, months to years. The only pathway that terminates outside itself.",
      "confidence": 0,
      "transmissibility": "Candidate",
      "requiresSkill": [
        "fifteen-ps",
        "pattern-writing"
      ],
      "fallback": "graph-tool",
      "source": "15 Ps (marc.relocalizecreativity.net)",
      "steps": [
        {
          "question": "What do we notice, and what might it become?",
          "tool": null,
          "does": "Private — Perception, Possibility, Purpose, Passion. Sensation before language.",
          "gate": null,
          "produces": "A felt purpose",
          "handoff": "These four are easily missed because they are not yet in words. A group that skips them builds something nobody wants."
        },
        {
          "question": "Who will commit, who do we bring in, what do we decide?",
          "tool": null,
          "does": "Public — Promise, Political Action, Policy.",
          "gate": "No program without a promise. Planning entered before anyone has committed produces plans nobody owns.",
          "produces": "Commitments and an enabling decision",
          "handoff": "Political action is repeating the first five in each other person."
        },
        {
          "question": "How will the work be organized and resourced?",
          "tool": null,
          "does": "Planning — Program, Project, Process.",
          "gate": null,
          "produces": "A resourced plan",
          "handoff": "Programs carry resources, projects carry sub-plans, processes create a reliable sequence."
        },
        {
          "question": "Does it get made, bought, delivered and kept safe?",
          "tool": null,
          "does": "Production — Product, Persuade, Purchase, Provide, Protect.",
          "gate": null,
          "produces": "A delivered good or service",
          "handoff": "Protect includes maintenance, disposal, recycling and the liabilities of failure — where most well-meant neighbourhood projects quietly stop."
        },
        {
          "question": "What is universal here that someone else could use?",
          "tool": null,
          "does": "Posterity — abstract what is general and publish it as a pattern.",
          "gate": null,
          "produces": "A new pattern on the shelf",
          "handoff": "This is the move from model to pattern. Posterity is not the end of this pathway — it is the input to everyone else's Systemic Problem Solving. If we do not share the recipes, innovations will not spread fast enough to matter."
        }
      ]
    },
    {
      "id": "systems-dynamics-pathway",
      "name": "Systems Dynamics",
      "kind": "curricular",
      "problem": "A person needs to learn to model causality, in an order that builds.",
      "context": "Named in the SODOTO Skills Registry. A learning progression, not a work progression — nobody runs a project in this order.",
      "confidence": null,
      "transmissibility": "Active",
      "fallback": "graph-tool",
      "source": "SODOTO Skills Registry, Observations",
      "skillOrder": [
        "causal-loop-diagramming",
        "stock-flow-modeling",
        "system-dynamics-modeling",
        "vesters-sensitivity-modeling"
      ]
    },
    {
      "id": "organizational-diagnosis-pathway",
      "name": "Organizational Diagnosis",
      "kind": "curricular",
      "problem": "A person needs to learn to see whether an organization is viable.",
      "context": "Named in the SODOTO Skills Registry.",
      "confidence": null,
      "transmissibility": "Ready",
      "fallback": "graph-tool",
      "source": "SODOTO Skills Registry, Observations",
      "skillOrder": [
        "sofi-vsm",
        "vsm",
        "eip-stage-sketching",
        "six-context-questions"
      ]
    },
    {
      "id": "sense-making-pathway",
      "name": "Sense-Making",
      "kind": "curricular",
      "problem": "A person needs to learn to tell what kind of situation they are in before acting.",
      "context": "Named in the SODOTO Skills Registry. Note where it ends — at the two governing models. The curriculum already teaches toward the crown.",
      "confidence": null,
      "transmissibility": "Candidate",
      "fallback": "graph-tool",
      "source": "SODOTO Skills Registry, Observations",
      "skillOrder": [
        "cynefin",
        "dsrp",
        "social-action-tetrahedron",
        "social-system-tetrahedron"
      ]
    },
    {
      "id": "mapping-pathway",
      "name": "Mapping",
      "kind": "curricular",
      "problem": "A person needs to learn to make the flows and relations of a place visible.",
      "context": "Named in the SODOTO Skills Registry.",
      "confidence": null,
      "transmissibility": "Candidate",
      "fallback": "graph-tool",
      "source": "SODOTO Skills Registry, Observations",
      "skillOrder": [
        "process-mapping",
        "linkage-mapping",
        "value-stream-mapping",
        "story-mapping",
        "arrows-diagram-graphviz"
      ]
    },
    {
      "id": "fedwiki-civic-practice-pathway",
      "name": "FedWiki Civic Practice",
      "kind": "curricular",
      "problem": "A person needs to learn to keep a neighbourhood's record and pass on what it learns.",
      "context": "Named in the SODOTO Skills Registry. Ends in Pattern Writing, which is how the shelf grows.",
      "confidence": null,
      "transmissibility": "Candidate",
      "fallback": "graph-tool",
      "source": "SODOTO Skills Registry, Observations",
      "skillOrder": [
        "fedwiki",
        "local-newspaper-fedwiki",
        "conversation-taxonomy",
        "pattern-writing"
      ]
    },
    {
      "id": "formal-modeling-pathway",
      "name": "Formal Modeling",
      "kind": "curricular",
      "problem": "A person needs to learn to specify a designed system precisely.",
      "context": "Named in the SODOTO Skills Registry.",
      "confidence": null,
      "transmissibility": "Candidate",
      "fallback": "graph-tool",
      "source": "SODOTO Skills Registry, Observations",
      "skillOrder": [
        "object-process-methodology",
        "model-based-systems-engineering",
        "bayesian-belief-modeling"
      ]
    }
  ]
};
